### ISSUE TITLE
Unrecoverable error when searching some non-existent subreddits

### ISSUE THREAD

**Issue by maxpsz** [Rafacv23/redditly#1]
When searching for some subreddits that doesn't exist, the app throws an error. Additionally, the non-existent subreddit gets added to the "recent visits" list, and there is no option to remove it. Clicking on this item causes the app to fail again, resulting in a broken experience.

**Steps to Reproduce:**
Open the search modal.
Search for a non-existent subreddit (e.g., "espania", "espaniol").
Observe that the app throws an error, having to refresh the app to return to a working state.

**Expected Behavior:**
The app should handle non-existent subreddit searches gracefully, having a way to return to a working state.
Non-existent subreddits searches may not be added to the "recent visits" list.

**Actual Behavior:**
The app thows an error when searching for a non-existent subreddit.
The non-existent subreddit is added to "recent visits".
Clicking on it results in the same error, preventing proper app usage.

Screenshots or Logs:
![image](https://github.com/user-attachments/assets/4c61b174-d2bc-4058-b6ad-bfff51536fa7)
![image](https://github.com/user-attachments/assets/14f3bbc7-deb1-4585-8424-a87d0121bdb3)
![image](https://github.com/user-attachments/assets/af3cb400-1a3d-4fef-a2b7-3ecd8031b064)
![image](https://github.com/user-attachments/assets/fdbc9733-3eac-47b6-83c6-ee145867bd46)

**Comment by maxpsz** [comment]
@Rafacv23 Nice work BTW!

**Comment by Rafacv23** [comment]
![dawdwadawdawdadaw-Redditly-09-23-2024_04_11_PM](https://github.com/user-attachments/assets/e5ab47ff-3fd7-458e-bf59-854245755f48)


Fixed, now the user will have a not found page and the subreddit searched it's not added to the recently added section.
